name: release-testpypi
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: http://test.pypi.org/p/huv

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - run: uv build
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
